version: '3'
services:
  # INFRAESTRUCTURA DE MENSAJERÍA (KAFKA)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # BASES DE DATOS (POSTGRESQL)
  catalog-db:
    image: postgres:15
    env_file: ./services/catalog/.env
    ports:
      - "${CATALOG_DB_PORT}:5432" # Puerto 5433 para Catálogo
  orders-db:
    image: postgres:15
    env_file: ./services/orders/.env
    ports:
      - "${ORDERS_DB_PORT}:5432" # Puerto 5434 para Pedidos      
  payment-db:
    image: postgres:15
    env_file: ./services/payment/.env
    ports:
      - "${PAYMENT_DB_PORT}:5432" # Puerto 5435 para Payment
      
  auth-db:
    image: postgres:15-alpine
    env_file: ./services/auth/.env
    ports:
      - "${AUTH_DB_PORT}:5432" # Puerto 5436 para Auth
    